<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2012/08/19 16:13:51

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=formulario',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
